mode: 1             # 1: distill training inpainting model ; 2: training dual Teacher
description: 'train with MAT'
restore_training: false  #restore from the last training stage
datasetName: Place
Generator: MobileFill
Discriminator: MultidilatedNLayerDiscriminatorWithAtt
train_dataDir: /data1/qfh/data/place/train_large
val_dataDir: /data1/qfh/data/place/real_imgs
maskDir: /data1/qfh/data/mask/testing_mask_dataset
val_maskDir: /data1/qfh/data/place/masks
lossNetDir: ./checkpoints
teacher_path: ./checkpoints/MAT/place/Places_512_FullData.pkl
loss_type : 'seg'       # seg/vgg  The pretrained network to calculate perceptual loss
saveDir : './checkpoints'
saveName: ''
log_path : './log'
val_saveDir : './results'
mask_type: 'medium_512' #medium_256/medium_512/thick_256/thick_512/thin_256/thin_512/segm_256/segm_512
gpuIDs:        #indicate different GPU device for training
- 0
num_workers: 8
val_step: 25000       #the frequency of validating and saving models
max_val_batches : 5000 #the maximum validate batches each time
targetSize : 512
is_training : True  #remove the co-learning branch when set to false
center_crop: false
batchSize : 4
val_batchSize: 20
maskType : 0        #'mask type: 0-external masks(random),  1-random free-form,  2-random square,  3-external masks(fixed),4-segmentation')
val_maskType : 3
max_iter : 1000000
iteration: 0
gan_loss_type: 'R1'
use_feat_map: false
use_sigmoid: false #set to false when using hinge/softplus/MSE as gan loss
load_last: true    #whether resume training from the last checkpoint
load_from_iter:
debug: False
seed: 2023   #random seed
enable_teacher: true
enable_ema: True
syn_param: True
D_input_type: "comp_img"


# learning rate
lr : 0.0006
d_lr : 0.00006
lr_steps: 4      #minimum training steps before adjust the learning rate
lr_factor: 0.95  #learning rate dropping factor
lr_decrease: false
min_lr: 0.0001
min_d_lr: 0.00001


#log args
print_loss_step: 50
save_im_step: 1000
record_training_imgs: false #whether to record the training images in tensorboard
record_val_imgs: false      #whether to record the validate images in tensorboard

#optimizer args
beta_g_min: 0.5
beta_g_max: 0.9
beta_d_min: 0
beta_d_max: 0.9


#loss args
use_rec_loss: True
use_rec_freq_loss: True
use_gan_loss: True
use_perc_loss: True
use_feat_map: False
lambda_gen: 1.5
lambda_hole: 3
lambda_valid: 3
lambda_perc: 4
lambda_style: 1
lambda_feat_mat: 1
lambda_r1: 0.001
d_reg_every: 16


#other tricks
use_grad_norm: false
max_grad_norm: 11
grad_norm_type: 2
acc_steps: 4        #gradient accumalation steps (1 means no accumalation)

